export const UPDATE_CARD = 'UPDATE_CARD';
export const SELECT_CARD = 'SELECT_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';
export const CREATE_CARD = 'CREATE_CARD';

export const FETCH_CARDS_START = 'FETCH_CARDS_START';
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
