export const UPDATE_CARD = 'UPDATE_CARD';
export const SELECT_CARD = 'SELECT_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';
export const CREATE_CARD = 'CREATE_CARD';

export const FETCH_CARDS_START = 'FETCH_CARDS_START';
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const TOGGLE_VIEW_ONLY_MODE_CHECK = 'TOGGLE_VIEW_ONLY_MODE_CHECK';
export const TOGGLE_MGMT_MODE_CHECK = 'TOGGLE_MGMT_MODE_CHECK';